kind: pipeline
type: docker
name: ci-java8

volumes:
  - name: maven_local_repo
    host:
      path: /mnt/data/maven_local_repo

steps:
  - name: build
    image: maven:3-jdk-8
    volumes:
      - name: maven_local_repo
        path: /root/.m2
    commands:
      - mvn install -s settings.xml -B -U

  - name: email
    image: drillster/drone-email
    settings:
      recipients_only: true
      recipients: [williamsrlin@outlook.com]
      subject: News from Drone CI
      host: smtp.mailgun.org
      port: 587
      from: drone@xdevops.cn
      username:
        from_secret: SMTP_USERNAME
      password:
        from_secret: SMTP_PASSWOR
      when:
        status: [ success, failure ]
