kind: pipeline
type: docker
name: ci-java8

volumes:
  - name: maven_local_repo
    host:
      path: /mnt/data/maven_local_repo


steps:
  - name: email
    image: drillster/drone-email
    settings:
      recipients_only: true
      recipients:
        - williamsrlin@outlook.com
        - williamsrlin@outlook.com
      subject: "Drone build ${build.status} for ${repo.name}"
      host: smtp.mailgun.org
      port: 587
      from: drone@xdevops.cn
      username:
        from_secret: mail_user
      password:
        from_secret: mail_password
      when:
        status: [ success, failure ]
