kind: pipeline
type: docker
name: ci-java8

volumes:
  - name: maven_local_repo
    host:
      path: /mnt/data/maven_local_repo


steps:
  - name: build
    image: maven:3-jdk-8
    volumes:
      - name: maven_local_repo
        path: /root/.m2
    commands:
      - mvn install -s settings.xml -B -U

  - name: email
    image: drillster/drone-email
    settings:
      recipients_only: true
      recipients:
        from_secret: email_recipients
      subject: "Drone build: [{{ build.status }}] {{ repo.name }} ({{ repo.branch }}) #{{ build.number }}"
      host: smtp.mailgun.org
      port: 587
      from: noreply@xdevops.cn
      username:
        from_secret: email_user
      password:
        from_secret: email_password
      when:
        status: [ success, failure ]

