kind: pipeline
type: docker
name: ci-java8

volumes:
  - name: maven_local_repo
    host:
      path: /mnt/data/maven_local_repo

steps:
  - name: build
    image: maven:3-jdk-8
    volumes:
      - name: maven_local_repo
        path: /root/.m2
    commands:
      - mvn install -s settings.xml -B -U

  - name: email
    image: drillster/drone-email
    host:
      - from_secret: SMPT_SERVER
    username:
      - from_secret: SMTP_USERNAME
    password:
      - from_secret: SMTP_PASSWOR
    from:
      - from_secret: EMAIL_FROM
    recipients:
      - from_secret: EMAIL_TO
    recipients_only: true
    when:
      status: [ success, failure ]


